#
# BASH CONFIG
#

# obsolete with fish
# set window title to working directory
#PROMPT_COMMAND='echo -en "\033]0;$(pwd)\a"'

#
# ENVIRONMENT VARIABLES
#

# bash is fine as an initial login shell (its usually the default across linux), i just immediately switch to fish for the rest of my user stuff
exec fish
