# make ssh work on guix foreign distro
# not needed for guix distro????
# but arch needs this and probably debian
# when nss-certs is installed
export SSL_CERT_DIR="$HOME/.guix-profile/etc/ssl/certs"
export SSL_CERT_FILE="$HOME/.guix-profile/etc/ssl/certs/ca-certificates.crt"
export GIT_SSL_CAINFO="$SSL_CERT_FILE"
export PATH="$HOME/.local/bin:$PATH"

footssh() {
	TERM=linux ssh $@
}
alias ssh=footssh

newterminal() {
    LF_LEVEL=0 foot > /dev/null 2> /dev/null &
}
alias new=newterminal

alias nmtui='TERM=linux nmtui'
# use lf sixels fork
# todo find a way to install binaries to guix
# or figure out guix packaging lol
# only if it exists
if [ -f /usr/local/bin/lf ]; then
    alias lf='/usr/local/bin/lf'
fi

# set window title to working directory
PROMPT_COMMAND='echo -en "\033]0;$(pwd)\a"'

if [ -z "$LF_LEVEL" ] || [ "$LF_LEVEL" -eq 0 ]; then
    # only if it exists
    if which lf > /dev/null; then
        exec lf
    fi 
fi
